name: aletheia-workflows
version: 0.1.0
workflows:
  - ./truth_oracle
  - ./rebalance_oracle
rpcs:
  - chain-name: ethereum-testnet-sepolia
    url: https://ethereum-sepolia-rpc.publicnode.com
  - chain-name: ethereum-testnet-sepolia-base-1
    url: https://sepolia.base.org
  - chain-name: ethereum-testnet-sepolia-optimism-1
    url: https://sepolia.optimism.io
  - chain-name: ethereum-testnet-sepolia-arbitrum-1
    url: https://sepolia-rollup.arbitrum.io/rpc
  - chain-name: avalanche-testnet-fuji
    url: https://api.avax-test.network/ext/bc/C/rpc
targets:
  staging:
    config: ./truth_oracle/config.staging.json
