name: aletheia-workflows
version: 0.1.0
workflows:
  - ./truth_oracle
rpcs:
  - chain-name: ethereum-testnet-sepolia
    url: https://ethereum-sepolia-rpc.publicnode.com
targets:
  staging:
    config: ./truth_oracle/config.staging.json
