// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {ReceiverTemplate} from "./ReceiverTemplate.sol";

/**
 * @title ProofRegistry
 * @notice An on-chain registry for storing zkSNARK proofs tied to specific interaction IDs (chequeIds).
 * @dev Inherits from ReceiverTemplate to securely receive valid reports from the Chainlink CRE DON.
 */
contract ProofRegistry is ReceiverTemplate {
    // Mapping from Cheque ID to the corresponding serialized zkSNARK proof
    mapping(bytes32 => bytes) public proofs;

    // Events
    event ProofRegistered(bytes32 indexed chequeId, bytes proof);

    /**
     * @notice Constructor
     * @param _forwarderAddress The address of the CRE Forwarder mapped to the target chain.
     */
    constructor(
        address _forwarderAddress
    ) ReceiverTemplate(_forwarderAddress) {}

    /**
     * @notice Processes a validated CRE report containing a single ZK proof payload.
     * @dev Called by ReceiverTemplate.onReport after forwarder validation passes.
     * @param report ABI-encoded (bytes32 chequeId, bytes proof).
     */
    function _processReport(bytes calldata report) internal override {
        // Decode the report payload generated by the proof_oracle workflow
        (bytes32 chequeId, bytes memory proof) = abi.decode(
            report,
            (bytes32, bytes)
        );

        // Registry maps the chequeId to the proof
        proofs[chequeId] = proof;

        // Emit an event for indexers
        emit ProofRegistered(chequeId, proof);
    }
}
